# Linux Build Configuration for Travis

language: cpp

os:
  - linux
  - osx

# Use Ubuntu 14.04 LTS (Trusty) as the Linux testing environment.
dist: trusty
sudo: false

env:
  global:
    - secure: V4cA44BEjfG2DluMxmz0I07h7LMEo41AP32/wv2YvjqsINr8ZIa7WvCV5CJpHhnsvM+5Y5EQ7l62yAioCIKL8U2a8m17t+2GnSceXqfZWc+GXsr8UTSnu8S5TmdSX9olMd78GJF4X/4AAJbbB4P4B+XRG0Zxvl9UK+Rp6l/cfW2q7/EJv1bgbPyFthNwEW9tOH7lRZv0fBHudJTHjFROcTi7I4rMXtUiiJDNp4Acad7dNyR84NBt+HNgW7rlvrPEcP3iik3FzGAfa2rHe3hzzWMuckzhuTqlkZ4Ai2dgFmr0LCmodCC5biNe+oQzed3Qe7mF3iOubVdNVe5oKdjiTKrWUjo18BhcoHlISC2R3pyJHscRTwQzIrl2te4t2yY9s/v7bGr/n+bqHiJsJV8x73JjtnWWgDd7Ft6yP+FmxyzKV4AdWGicmzoe0hAsg6yIlBw/EnNW3LXQgq6gpgruXt+2vhRfFRQyIjFGwtpTn3FNR2kPBTB8VOVKT2vGN3ISABeY0p2Ro2i9tst2upfxAOuWwOADlMymLwShc+GBpP2tS8D3pXxCNA9xIzLP+X7RFNtysYiNa2afBMyuizsJcg1WLm8aOIF5jzyiy2ZSuuOV6OqpJGafKUR3UmgRXaptRUJqpvZ5+ABCpSeBHMFrTjPfpZu0NAa298KY9lIpCEE=
  matrix:
    # Each line is a set of environment variables set before a build.
    # Thus each line represents a different build configuration.
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

compiler:
  - clang
  - gcc

matrix:
  fast_finish: true
  include:
    # Additional build using Android NDK with android-cmake
    - env: BUILD_ANDROID_CMAKE=ON
    # Additional build using Android NDK with Android.mk
    - env: BUILD_ANDROID_MK=ON
  exclude:
    # Skip GCC builds on macOS.
    - os: osx
      compiler: gcc

cache:
  apt: true

git:
  depth: 1

branches:
  only:
    - master

before_install:
  - if [[ "$BUILD_ANDROID_CMAKE" == "ON" ]] || [[ "$BUILD_ANDROID_MK" == "ON" ]]; then
      git clone --depth=1 https://github.com/urho3d/android-ndk.git $HOME/android-ndk;
      export ANDROID_NDK=$HOME/android-ndk;
      git clone --depth=1 https://github.com/taka-no-me/android-cmake.git $HOME/android-cmake;
      export TOOLCHAIN_PATH=$HOME/android-cmake/android.toolchain.cmake;
    fi

before_script:
  - git clone --depth=1 https://github.com/KhronosGroup/SPIRV-Headers external/spirv-headers
  - git clone --depth=1 https://github.com/google/googletest          external/googletest

script:
  # Due to the limitation of Travis platform, we cannot start too many concurrent jobs.
  # Otherwise GCC will panic with internal error, possibility because of memory issues.
  # ctest with the current tests doesn't profit from using more than 4 threads.
  - export NPROC=4;
  - mkdir build && cd build;
  - if [[ "$BUILD_ANDROID_MK" == "ON" ]]; then
      export BUILD_DIR=$(pwd);
      mkdir ${BUILD_DIR}/libs;
      mkdir ${BUILD_DIR}/app;
      $ANDROID_NDK/ndk-build -C ../android_test NDK_PROJECT_PATH=.
                             NDK_LIBS_OUT=${BUILD_DIR}/libs
                             NDK_APP_OUT=${BUILD_DIR}/app -j${NPROC};
    elif [[ "$BUILD_ANDROID_CMAKE" == "ON" ]]; then
      cmake -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_PATH}
            -DANDROID_NATIVE_API_LEVEL=android-9
            -DCMAKE_BUILD_TYPE=Release
            -DANDROID_ABI="armeabi-v7a with NEON"
            -DSPIRV_BUILD_COMPRESSION=ON
            -DSPIRV_SKIP_TESTS=ON ..;
      make -j${NPROC};
    else
      cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DSPIRV_BUILD_COMPRESSION=ON -DCMAKE_INSTALL_PREFIX=install ..;
      make -j${NPROC} install;
      ctest -j${NPROC} --output-on-failure --timeout 300;
    fi

after_success:
  # Create tarball for deployment
  - if [[ "${CC}" == "clang" && "${BUILD_ANDROID_MK}" != "ON" && "${BUILD_ANDROID_CMAKE}" != "ON" ]]; then
      cd install;
      export TARBALL=SPIRV-Tools-master-${TRAVIS_OS_NAME}-${BUILD_TYPE}.zip;
      find . -print | zip -@ ${TARBALL};
    fi

before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "builds@travis-ci.org"
  - git tag -f master-tot
  - git push -q -f https://${TAGPERM}@github.com/antiagainst/SPIRV-Tools --tags

deploy:
  provider: releases
  api_key: ${TAGPERM}
  on:
    branch: master
    condition: ${CC} == clang && ${BUILD_ANDROID_MK} != ON && ${BUILD_ANDROID_CMAKE} != ON
  file: ${TARBALL}
  skip_cleanup: true
  overwrite: true

notifications:
  email:
    recipients:
      - andreyt@google.com
      - antiagainst@google.com
      - awoloszyn@google.com
      - dneto@google.com
      - ehsann@google.com
      - qining@google.com
    on_success: change
    on_failure: always
